#!/usr/bin/env bash

BASE_DIR=$(dirname "$0")

RESTAKING_PROGRAM_KEYPAIR_FILE="$BASE_DIR/restaking/devnet_program_frag9zfFME5u1SNhUYGa4cXLzMKgZXF3xwZ2Y1KCYTQ.json"
RESTAKING_PROGRAM_TARGET_KEYPAIR_DIR="$BASE_DIR/../target/deploy"
RESTAKING_PROGRAM_TARGET_KEYPAIR_FILE="$RESTAKING_PROGRAM_TARGET_KEYPAIR_DIR/restaking-keypair.json"

echo "[*] Creating a symbolic link to $RESTAKING_PROGRAM_TARGET_KEYPAIR_FILE pointing $RESTAKING_PROGRAM_KEYPAIR_FILE"
mkdir -p "$RESTAKING_PROGRAM_TARGET_KEYPAIR_DIR" && rm -f "$RESTAKING_PROGRAM_TARGET_KEYPAIR_FILE" && ln -s "$RESTAKING_PROGRAM_KEYPAIR_FILE" "$RESTAKING_PROGRAM_TARGET_KEYPAIR_FILE"